[package]
name = "qr_coder"
version = "0.1.0"
authors = ["swkfn <sw.kfn4410uec@gmail.com>"]
description = "Create QRcode from any string"

[dependencies]
clap = "2.31"
failure = "0.1"
qrcode = "0.5"
image = "0.17"